language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: wasm-pack stable
      before_script:
        - rustup target add wasm32-unknown-unknown
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - cd wasmdemos
        - wasm-pack build -- -p m4vga-wasm-demos
 
before_script:
  - rustup target add thumbv7em-none-eabihf
  - sudo apt-get install gcc-arm-none-eabi
script:
  - cargo build --verbose
  - cargo test -p gfx --target=x86_64-unknown-linux-gnu
